routes/web.php
Route::post('/buyer-reply-edit-save', 'AccountController@buyer_reply_edit_save')->name('buyer_reply_edit_save');
Route::get('/billing', 'AccountController@billing')->name('billing');
Route::get('/invoice-detail', 'AccountController@invoice_detail')->name('invoice_detail');
Route::get('/payment', 'AccountController@payment')->name('payment');
Route::get('/getInfoPayment', 'AccountController@getInfoPayment');
Route::post('/payment-save', 'AccountController@payment_save')->name('payment_save');

Route::get('/sale-detail', 'AccountController@sale_detail')->name('sale_detail');
Route::get('/sales', 'AccountController@sales')->name('sales');
Route::get('/seller-qualification', 'AccountController@seller_qualification')->name('seller_qualification');
Route::post('/seller-qualification-save', 'AccountController@seller_qualification_save')->name('seller_qualification_save');
Route::get('/seller-qualification-edit', 'AccountController@seller_qualification_edit')->name('seller_qualification_edit');
Route::post('/seller-qualification-edit-save', 'AccountController@seller_qualification_edit_save')->name('seller_qualification_edit_save');
Route::post('/qualification-seller', 'AccountController@qualification_seller')->name('qualification_seller');
Route::get('/seller-reply-edit', 'AccountController@seller_reply_edit')->name('seller_reply_edit');
Route::post('/seller-reply-edit-save', 'AccountController@seller_reply_edit_save')->name('seller_reply_edit_save');
Route::post('/save-note', 'AccountController@save_note')->name('save_note');
Route::post('/update-note', 'AccountController@update_note')->name('update_note');
Route::post('/delete-note', 'AccountController@delete_note')->name('delete_note');
Route::get('/charged', 'AccountController@charged')->name('charged');


Route::get('/publications', 'AccountController@publications')->name('publications');
Route::get('/plan', 'AccountController@plan')->name('plan');
Route::post('/save-plan', 'AccountController@save_plan')->name('save_plan');
Route::get('/pause', 'AccountController@pause')->name('pause');
Route::get('/activate', 'AccountController@activate')->name('activate');
Route::get('/finish', 'AccountController@finish')->name('finish');
Route::get('/shipping-cost', 'AccountController@shipping_cost')->name('shipping_cost');
Route::post('/shipping-cost-save', 'AccountController@shipping_cost_save')->name('shipping_cost_save');
Route::get('/change-category/{id}', 'AccountController@change_category')->name('change-category');
Route::post('/save-change-category', 'AccountController@save_change_category')->name('save-change-category');
Route::get('/modify-publication/{id}', 'AccountController@modify_publication')->name('modify-publication');
Route::post('/modify-publication-save', 'AccountController@modify_publication_save')->name('modify-publication-save');
Route::get('/questions', 'AccountController@questions')->name('questions');
Route::post('/answer-questions', 'AccountController@answer_questions')->name('answer-questions');
Route::get('/republish-publication/{id}', 'AccountController@republish_publication')->name('republish-publication');
Route::post('/republish-publication-save', 'AccountController@republish_publication_save')->name('republish-publication-save');
Route::get('/seller/request-change-qualification', 'AccountController@seller_request_change_qualification')->name('seller_request_change_qualification');
Route::get('/buyer-qualification-confirm', 'AccountController@buyer_qualification_confirm')->name('buyer_qualification_confirm');
Route::get('/buyer/request-change-qualification', 'AccountController@buyer_request_change_qualification')->name('buyer_request_change_qualification');
Route::get('/seller-qualification-confirm', 'AccountController@seller_qualification_confirm')->name('seller_qualification_confirm');
Route::get('/stock', 'AccountController@stock')->name('stock');
Route::post('/stock-save', 'AccountController@stock_save')->name('stock_save');

// Addresses
Route::get('/newaddress', 'AccountController@new_address');
Route::post('/addaddress', 'AccountController@add_address');
Route::get('/edit_address/{id}', 'AccountController@edit_address');
Route::post('/modaddress', 'AccountController@mod_address');
Route::get('/use_address_for_sales/{id}', 'AccountController@use_address_for_sales');
Route::get('/use_address_for_purchases/{id}', 'AccountController@use_address_for_purchases');
Route::get('/remove_address/{id}', 'AccountController@remove_address');
Route::post('/set_send_with_email', 'AccountController@set_send_with_email');
Route::post('/save-message', 'AccountController@save_message')->name('save_message');

// Emails
Route::get('/emails', 'AccountController@email_preferences');
Route::post('/update_emails', 'AccountController@update_email_preferences');

//Reputation
Route::get('/myreputation', 'AccountController@index');
Route::get('/reputationseller', 'ReputationController@reputation_as_seller')->name('reputationseller');
Route::get('/reputationbuyer', 'ReputationController@reputation_as_buyer')->name('reputationbuyer');

Route::get('/execute-cron', 'CronController@execute')->name('execute_cron');

Route::get('/help', 'HelpController@index')->name('help');
Route::get('/contact', 'ContactController@index')->name('contact');
Route::post('/send-contact', 'ContactController@send_contact')->name('send_contact');

Route::get('/photo/{size}', function($size = NULL){
	$name = Illuminate\Support\Facades\Input::get('url');
    if(!is_null($size) && !is_null($name)){
        $size = explode('x', $size);
        $cache_image = Image::cache(function($image) use($size, $name){
           //return $image->make($name)->fit($size[0], $size[1]);
			if(File::exists('uploads/images/products/'.$name)) {
                $output = $image->make('uploads/images/products/'.$name)->fit($size[0], $size[1]);
            } else {
                $output = $image->make('uploads/images/products/nophoto.jpg');
            }
            return $output;
        }, 10); // cache for 10 minutes

        return Response::make($cache_image, 200, ['Content-Type' => 'image']);
    } else {
        abort(404);
    }
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::resource('bank-account','BankAccountController');
    Route::resource('currency','CurrencyController');
    Route::get('/', 'Auth\LoginController@showLoginForm');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');//->name('admin.password.token');
    //Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    //Route::post('register', 'Auth\RegisterController@register');
    Route::get('home', 'HomeController@index')->name('admin_home');
    Route::post('home', 'HomeController@index');
    Route::get('user-detail/{id}', 'HomeController@user_detail')->name('user_detail');
    Route::get('user-modify/{id}', 'HomeController@user_modify')->name('user_modify');
    Route::post('user-modify_save', 'HomeController@user_modify_save')->name('user_modify_save');
    Route::get('user-invoices/{id}', 'HomeController@user_invoices')->name('user_invoices');
    Route::post('user-invoices/{id}', 'HomeController@user_invoices')->name('user_invoices');
    Route::get('user-invoice-detail/{id}', 'HomeController@user_invoice_detail')->name('user_invoice_detail');
    Route::get('user-invoice-payment/{id}', 'HomeController@user_invoice_payment')->name('user_invoice_payment');
    Route::get('change-payment-status/{id}', 'HomeController@change_payment_status')->name('change_payment_status');
    Route::get('change-leader-status/{id}', 'HomeController@change_leader_status')->name('change_leader_status');
    Route::get('user-purchases/{id}', 'HomeController@user_purchases')->name('user_purchases');
    Route::post('user-purchases/{id}', 'HomeController@user_purchases')->name('user_purchases');
    Route::get('user-sales/{id}', 'HomeController@user_sales')->name('user_sales');
    Route::post('user-sales/{id}', 'HomeController@user_sales')->name('user_sales');
    Route::get('seller-delete-qualification/{id}', 'HomeController@seller_delete_qualification')->name('seller_delete_qualification');
    Route::get('buyer-delete-qualification/{id}', 'HomeController@buyer_delete_qualification')->name('buyer_delete_qualification');
    Route::get('transaction-detail/{id}', 'HomeController@transaction_detail')->name('transaction_detail');
    Route::get('payment-invoices', 'HomeController@payment_invoices')->name('payment_invoices');
    Route::post('payment-invoices', 'HomeController@payment_invoices')->name('payment_invoices');

    Route::get('publications', 'HomeController@publications')->name('admin_publications');
    Route::post('publications', 'HomeController@publications')->name('admin_publications');
    Route::get('status-modify/{id}', 'HomeController@status_modify')->name('status_modify');
    Route::post('status-modify_save', 'HomeController@status_modify_save')->name('status_modify_save');
    Route::get('questions/{id}', 'HomeController@questions')->name('admin_questions');
    Route::post('questions/{id}', 'HomeController@questions')->name('admin_questions');
    Route::get('disable-question/{id}', 'HomeController@disable_question')->name('disable_question');
    Route::get('disable-answer/{id}', 'HomeController@disable_answer')->name('disable_answer');
    Route::get('enable-question/{id}', 'HomeController@enable_question')->name('enable_question');
    Route::get('enable-answer/{id}', 'HomeController@enable_answer')->name('enable_answer');

app/Currency.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Currency
 * @package App
 */
class Currency extends Model
{
    public $table = 'currencies';
    public $timestamps = false;
}

app/Models/Currency/Relationships/CurrencyRelationship.php
<?php
namespace App\Models\Currency\Relationships;

/**
 * Created by PhpStorm.
 * User: manuelcasco
 * Date: 12/04/20
 * Time: 02:44
 */
trait CurrencyRelationship
{

}

app/Http/Controllers/Admin/CurrencyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Currency;
use App\Http\Requests\CurrencyRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

/**
 * Class CurrencyController
 * @package App\Http\Controllers\Admin
 */
class CurrencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $currency_search = $request->isMethod('get') ? $request->get('currency-search') : $request->session()->pull('currency-search', '');

        $request->session()->put('currency-search', ($currency_search));
        $query = Currency::orderBy('name');
        if (!empty($currency_search)) {
            $query->where('name', 'like', "%$currency_search%")
                ->orWhere('symbol', 'like', "%$currency_search%")
                ->orWhere('id', 'like', "%$currency_search%");
        }
        $currencies = $query->paginate(10);
        return response()->view('admin.currencies.index',
            [
                'currencies' => $currencies,
                'currency_search' => $currency_search
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.currencies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CurrencyRequest $request)
    {
        $currency = new Currency();
        $currency->name = $request->input('name');
        $currency->symbol = $request->input('symbol');
        $currency->save();
        return redirect('admin/currency')->with(['message' => 'Succesfully created an currency']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $currency = Currency::findOrFail($id);
        return view('admin.currencies.edit')->with(['currency' => $currency]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(CurrencyRequest $request, $id)
    {
        $currency = Currency::findOrFail($id);
        $currency->name = $request->input('name');
        $currency->symbol = $request->input('symbol');
        $currency->save();
        return redirect('admin/currency')->with(['message' => 'Succesfully created an currency']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $currency = Currency::findOrFail($id);
        $currency->delete();
        return redirect('admin/currency')->with(['message' => 'Currency Deleted Succesfully']);
    }
}

resources/views/admin/currencies/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <form method="POST" action="{{ route('currency.store') }}">
            {{ csrf_field() }}
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="pull-left">Crear Moneda</h4>
                            <a href="{{ route('home') }}" class="btn btn-default pull-right">Regresar</a>
                            <div class="clearfix"></div>
                        </div>
                        <div class="panel-body">
                            <!-- Table -->
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Campo</th>
                                        <th>Valor</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <th>Nombre</th>
                                        <td>
                                            <input id="name" type="text" class="form-control" name="name" value="">
                                            @if ($errors->has('name'))
                                                <span class="help-block">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                            @endif
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Symbol</th>
                                        <td>
                                            <input id="symbol" type="text" class="form-control" name="symbol" value="">
                                            @if ($errors->has('symbol'))
                                                <span class="help-block">
                                            <strong>{{ $errors->first('symbol') }}</strong>
                                        </span>
                                            @endif
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2" style="text-align: right"><button type="submit" class="btn btn-primary">Guardar</button></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/currencies/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <form method="post" action="{{url('admin/currency/'.$currency->id)}}">
            {{method_field('PUT')}}
            {{ csrf_field() }}
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="pull-left">Modificar Moneda: {{ $currency->name }} </h4>
                            <a href="{{ route('home') }}" class="btn btn-default pull-right">Regresar</a>
                            <div class="clearfix"></div>
                        </div>
                        <div class="panel-body">
                            <!-- Table -->
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Campo</th>
                                        <th>Valor</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <th>Nombre</th>
                                        <td>
                                            <input id="name" type="text" class="form-control" name="name" value="{{ $currency->name }}">
                                            @if ($errors->has('name'))
                                                <span class="help-block">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                            @endif
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Symbol</th>
                                        <td>
                                            <input id="symbol" type="text" class="form-control" name="symbol" value="{{ $currency->symbol }}">
                                            @if ($errors->has('symbol'))
                                                <span class="help-block">
                                            <strong>{{ $errors->first('symbol') }}</strong>
                                        </span>
                                            @endif
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2" style="text-align: right"><button type="submit" class="btn btn-primary">Guardar</button></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/currencies/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <!-- Default panel contents -->
                        <form method="GET" action="{{ url('/admin/currencies') }}">
                            <div class="panel-heading">
                                <h4 class="pull-left">Monedas</h4>
                                <div class="input-group col-md-4 pull-right" style="margin-top: 5px">
                                    <input type="text" class="form-control" name="currency-search" value="{{ $currency_search }}" placeholder="Buscar por: identificación, nombre, apellido ...">
                                    <span class="input-group-btn">
                                  <button class="btn btn-default" type="submit">Buscar</button>
                                </span>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            {{ csrf_field() }}
                        </form>
                    </div>
                    <div class="panel-body">
                        <!-- Table -->
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Identificación</th>
                                    <th>Nombre</th>
                                    <th>Simbolo</th>
                                    <th>&nbsp;</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if(count($currencies))
                                    @foreach($currencies as $currency)
                                        <tr>
                                            <td>{{ $currency->id }}</td>
                                            <td>{{ $currency->name }}</td>
                                            <td>{{ $currency->symbol }}</td>
                                            <td>
                                                <a href="{{ url('admin/currency/'.$currency->id.'/edit')}}" title="Modificar"><i class="glyphicon glyphicon-pencil"></i></a>
                                                {{--<form method="POST" action="{{url('admin/currency/'.$currency->id)}}">
                                                    {{method_field('DELETE')}}
                                                    {{csrf_field()}}
                                                    <button><i class="glyphicon glyphicon-trash"></i></button>
                                                </form>--}}
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr><td colspan="6"><div   class="alert alert-warning">No se encontraron registros</div></td></tr>
                                @endif
                                </tbody>
                            </table>
                        </div>
                        @if(count($currencies))
                            <div class="panel-footer" style="text-align: center">
                                {{ $currencies->links() }}
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection